services:
  clss-search-evaluator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clss-search-evaluator
    ports:
      - "8080:8080"
    environment:
      OUTPUT_DIR: /app/output
      DATASET_PATH: classpath:dataset/queries.json
      SEARCH_HOST: https://cursos.alura.com.br
      SEARCH_PATH: /test/learning-project/search
    volumes:
      - ./output:/app/output
