spring.application.name=clss-search-evaluator

search.host=http://localhost:8080
search.path=/test/learning-project/search
search.duration-floor=1
search.duration-ceiling=3

dataset.path=classpath:dataset/queries.json

output.dir=output

openai.model=gpt-5.4-mini
